server.error.whitelabel.enabled: false

springdoc:
  api-docs:
    # /api-docs endpoint custom path
    path: /api-docs
    # Disabling the /v3/api-docs enpoint
    #enabled: false
  swagger-ui:
    # swagger-ui custom path
    path: /swagger-ui.html
    # Disabling the swagger-ui
    #enabled: false
  show-login-endpoint: false

chat:
  store:
    r2dbc:
      url: r2dbc:postgresql://postgres:postgres@localhost:5432/northernlights-chat
      pool:
        name: chat-api-pool
        initial-size: 10
        max-size: 10
        max-idle-time: 30m
