server.error.whitelabel.enabled: false
logging:
  level:
    org.springframework.data.r2dbc: INFO
    io.r2dbc.pool: INFO
springdoc:
  api-docs:
    # /api-docs endpoint custom path
    path: /api-docs
    # Disabling the /v3/api-docs enpoint
    #enabled: false
  swagger-ui:
    # swagger-ui custom path
    path: /swagger-ui.html
    # Disabling the swagger-ui
    #enabled: false
  show-login-endpoint: false

chat:
  store:
    r2dbc:
      # url: r2dbc:postgresql://postgres:postgres@localhost:5432/northernlights-chat
      url: r2dbc:pool:postgresql://${CHAT_DB_USER}:${CHAT_DB_PASSWORD}@${CHAT_DB_HOST}:${CHAT_DB_PORT}/${CHAT_DB_NAME}
      pool:
#        name: chat-api-pool
        initial-size: 10
        max-size: 100
        max-idle-time: 30m
  redis:
    hostname: ${CHAT_REDIS_HOST}
    port: ${CHAT_REDIS_PORT}
    workspace: ${CHAT_REDIS_WORKSPACE}

  api:
    google-client-id: 183144544565-6pc3gk5er5419mo4gj0a4d8ev87iigkg