spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

## Debezium configuration
database:
#  hostname: northernlights-chat-db
#  port: 5432
#  dbname: northernlights-chat
#  user: postgres
#  password: postgres
  server.name: nl_chat_dbz


## Redis Information (bypassed using "local" spring profile)
chat.redis:
  workspace: northernlights
##  hostname: northernlights-chat-redis
##  port: 6379
